name: Build

on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2.4.0

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v2.5.0
              with:
                  node-version: 12

            - name: Build/release Electron app
              uses: michalzaq12/action-electron-nuxt@v1.5.0
              with:
                  github_token: ${{ secrets.github_token }}

                  # If the commit is tagged with a version (e.g. "v1.0.0")
                  # type: boolean
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
