name: Build

on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ${{ matrix.os }}
        permissions: write-all

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v3.2.0
              with:
                  node-version: 16

            - name: Use cache
              uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  github_token: ${{ secrets.github_token }}
                  max-attempts: "3"
                  args: --config electron-builder.config.js
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
