# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: main

on:
    push:
        branches: [master, next, beta, alpha]
    pull_request:
        branches: [master, next, beta, alpha]

permissions:
    packages: write
    contents: write
    issues: write
    pull-requests: write

jobs:
    default:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Use cache
              uses: actions/cache@v3
              with:
                   path: |
                        node_modules
                        */*/node_modules
                        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

            - name: Install
              run: |
                  npm ci

            - name: Build
              run: |
                  npm run build

            - name: Test
              run: |
                  npm run test

            - name: Release
              id: semantic
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release

            - name: Package
              if: steps.semantic.outputs.new_release_published == 'true'
              uses: samuelmeuli/action-electron-builder@v1
              with:
                   github_token: ${{ secrets.GITHUB_TOKEN }}
                   max-attempts: "3"
                   args: --config electron-builder.config.js
                   release: true
