# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: main

on:
    push:
        branches: [master, next, beta, alpha]
    pull_request:
        branches: [master, next, beta, alpha]

permissions:
    packages: write
    contents: write
    issues: write
    pull-requests: write

jobs:
    default:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install
              uses: ./.github/actions/install
              with:
                    node-version: 16.x

            - name: Build
              uses: ./.github/actions/build

            - name: Test
              run: |
                  npm run test

            - name: Release
              id: semantic
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
