# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: main

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3.4.0
              with:
                  node-version: ${{ matrix.node-version }}

            -   name: Use cache
                uses: actions/cache@v3
                with:
                    path: |
                        node_modules
                        */*/node_modules
                    key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

            - name: Build and install packages
              run: |
                yarn install
                yarn build
                yarn test
